-- Create table for site content if it doesn't exist
create table if not exists site_content (
  id bigint generated by default as identity primary key,
  section_key text not null unique,
  content jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table site_content enable row level security;

-- Policies
create policy "Public Read" on site_content for select using (true);
create policy "Auth Write" on site_content for insert with check (auth.role() = 'authenticated');
create policy "Auth Update" on site_content for update using (auth.role() = 'authenticated');

-- Insert default config for Magic Video Hub if not exists
insert into site_content (section_key, content)
values (
  'magic_video_hub',
  '{
    "livingBackgrounds": {
      "mediaType": "image",
      "mediaUrl": "", 
      "link": "/magic-video/living-backgrounds"
    },
    "directorsCut": {
      "mediaType": "image",
      "mediaUrl": "",
      "link": "/magic-video/directors-cut"
    },
    "instantClips": {
      "mediaType": "image",
      "mediaUrl": "",
      "link": "/magic-video/instant-clips"
    }
  }'::jsonb
)
on conflict (section_key) do nothing;
