-- Ensure site_content table exists
CREATE TABLE IF NOT EXISTS public.site_content (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_key TEXT NOT NULL UNIQUE,
    content JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Enable RLS
ALTER TABLE public.site_content ENABLE ROW LEVEL SECURITY;

-- Policies for site_content
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Public Read' AND tablename = 'site_content') THEN
        CREATE POLICY "Public Read" ON public.site_content FOR SELECT USING (true);
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Auth Write' AND tablename = 'site_content') THEN
        CREATE POLICY "Auth Write" ON public.site_content FOR INSERT WITH CHECK (auth.role() = 'authenticated');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Auth Update' AND tablename = 'site_content') THEN
        CREATE POLICY "Auth Update" ON public.site_content FOR UPDATE USING (auth.role() = 'authenticated');
    END IF;
END $$;

-- Initialize or update Terms and Privacy in plus_info_pages
-- Note: This assumes plus_info_pages key is used for both guides and policies.
-- We use a structured JSON that matching the PlusInfoEditor's GuidesContent interface.

INSERT INTO public.site_content (section_key, content)
VALUES ('plus_info_pages', '{
  "pages": {
    "terms": {
      "title": "Terms of Service",
      "description": "User Agreement & AI Responsibility",
      "content": "<h2>1. Acceptance of Terms</h2><p>By using ContentAI, you agree to these terms...</p><h2>2. AI Content Responsibility</h2><p>Users are solely responsible for the content they generate, recreate, or modify using our AI tools. ContentAI provides the technology, but the legal rights and responsibilities regarding intellectual property, copyright, and distribution belong to the User.</p>"
    },
    "privacy": {
      "title": "Privacy Policy",
      "description": "Data Handling & Protection",
      "content": "<h2>1. Data Collection</h2><p>We collect minimal data necessary for video generation...</p>"
    }
  }
}')
ON CONFLICT (section_key) DO UPDATE 
SET content = site_content.content || jsonb_build_object('pages', site_content.content->'pages' || '{
    "terms": {
      "title": "Terms of Service",
      "description": "User Agreement & AI Responsibility",
      "content": "<h2>1. Acceptance of Terms</h2><p>By using ContentAI, you agree to these terms. Our service allows you to use advanced AI models to recreate and edit videos.</p><h2>2. Intellectual Property & AI Generation</h2><p><strong>User Responsibility:</strong> You represent and warrant that you have all necessary rights, licenses, and permissions to any content (videos, images, products) you upload to ContentAI. You are solely responsible for ensuring that your use of the service and the resulting generated content does not infringe upon any third-party intellectual property rights.</p><p><strong>AI Content Ownership:</strong> Subject to your compliance with these terms, ContentAI assigns to you all its rights, title, and interest in and to the output generated by the service based on your inputs. However, due to the nature of machine learning, output may not be unique across users and the service may generate the same or similar output for other users.</p><h2>3. Prohibited Use</h2><p>You may not use the service to generate content that is illegal, harmful, or violates the rights of others.</p>"
    },
    "privacy": {
      "title": "Privacy Policy",
      "description": "Data Handling & Protection",
      "content": "<h2>1. Information We Collect</h2><p>We collect your email address for account management and the media you upload specifically for generation purposes. Media is stored securely and processed via our GPU clusters.</p><h2>2. Data Usage</h2><p>We use your data to provide the video generation service. We do not sell your personal data to third parties.</p>"
    }
}'::jsonb);
