create table if not exists site_content (
  id bigint generated by default as identity primary key,
  section_key text not null unique,
  content jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table site_content enable row level security;

create policy "Enable read access for all users"
  on site_content for select
  using (true);

create policy "Enable update for service role or authenticated users"
  on site_content for update
  using (auth.role() = 'authenticated') 
  with check (auth.role() = 'authenticated');

create policy "Enable insert for service role or authenticated users"
  on site_content for insert
  with check (auth.role() = 'authenticated');
